alias jn="jupyter notebook"
alias vs="code ."
alias jl="jupyter-lab"
alias dps="docker ps --format \"table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.RunningFor}}\t{{.Ports}}\""
alias dc="docker-compose"
alias dcps="/home/muy/repositories/dotfiles/dcps.py"