alias jn="jupyter notebook"
alias vs="code ."
alias jl="jupyter-lab"
alias dps="docker ps --format \"table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.RunningFor}}\t{{.Ports}}\""
alias dc="docker-compose"
alias mount-dev="sudo sshfs -o allow_other,default_permissions,IdentityFile=/home/muy/.ssh/id_rsa muy@dev08.ascarix.local:/home/muy/ /home/muy/dev08_home/"
alias connect-vpn="sudo openvpn --config /home/muy/immosparrow.ovpn"
